language: python
python:
    - "3.6"
install:
    - pip install pandas
    - pip install scikit-learn
    - pip install tensorflow
    - pip install keras
script: 
    - python setup.py build
    - python setup.py install